apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-e83abe727a3d44459199ba094881b6ca-depl
  labels:
    app: coll-e83abe727a3d44459199ba094881b6ca
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-e83abe727a3d44459199ba094881b6ca
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-e83abe727a3d44459199ba094881b6ca
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-e83abe727a3d44459199ba094881b6ca
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-e83abe727a3d44459199ba094881b6ca
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping